[project]
name = "langraph-agent-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["langgraph", "ipykernel", "langchain_openai",
 "dotenv", "langchain", "langchain_community", "typing"]

